// Action types
export const GET_ABSENTEES_SUCCESS = 'GET_ABSENTEES_SUCCESS';
export const GET_ABSENTEES_FAILURE = 'GET_ABSENTEES_FAILURE';
export const EXPORT_ABSENTEES_SUCCESS = 'EXPORT_ABSENTEES_SUCCESS';
export const EXPORT_ABSENTEES_FAILURE = 'EXPORT_ABSENTEES_FAILURE';
